# Generated by Django 6.0.5 on 2026-05-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('quero_ler', 'Quero ler'), ('lendo', 'Lendo'), ('lido', 'Lido'), ('pausado', 'Pausado')], default='quero_ler', max_length=20)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resenha', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
